### PR TITLE
support python3 run_data.sh

### PR DESCRIPTION
**Pull request by rgtjf**
support python3 for data preprocess

### CODE REVIEW

**Comment by uduse** [comment]
just wondering, is there a reason of using `codecs.open` instead of `open`?

**Comment by faneshion** [comment]
It's very nice for contributing your code @rgtjf.  I have the same question with uduse, why replace open with codecs.open?

**Comment by rgtjf** [comment]
python2:
   when using `open`, it may happen `UnicodeDecodeError` . Therefore, we could use codecs to encode `str` into `utf8`

python3:
  it can use `open` to set the file encoding. Moreover, `codecs.open`  also works.

Thus for Compatibility, I use `codecs.open` instead of `open`.

ref:
1. https://zhidao.baidu.com/question/1823800427851275948.html
1. http://python.jobbole.com/81244/

**Comment by rgtjf** [comment]
I will report the results soon

**Comment by rgtjf** [comment]
I run ARC-I twice, the results are following:

| Models | NDCG@3   | NDCG@5   | MAP      |
|--------|----------|----------|----------|
| ARC-I  | 0.5680   | 0.6317   | 0.5870   |
| Run1   | 0.562959 | 0.626947 | 0.580135 |
| Run2   | 0.573168 | 0.637427 | 0.589967 |

Note:
1. I obtain `18677` tokens in file `word_dict.txt`, while the origin is `18670`. To run the code, I also modify the `vocab_size`  in the config file.

**Pull request merged**
